version: '3.1'

services:

  mariadb:
    image: mariadb:latest
    restart: 'always'
    volumes:
      - ./mariaDB/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_prod
    ports:
        - "3306:3306"