# Use root/example as user/password credentials
version: "3.1"

services:
  mongo:
    image: mongo
    container_name: data-db
    restart: "no"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: db
    volumes:
      - ./docker/mongodb/db:/data/db
      - ./docker/mongodb/logs:/var/log/mongodb
    command:
      ["mongod", "--logpath", "/var/log/mongodb/mongodb.log", "--logappend"]
    deploy:
      resources:
        limits:
          memory: 4g
          cpus: "2.0"
        reservations:
          memory: 2g
    ports:
      - "27017:27017"

  mariadb:
    image: mariadb
    container_name: log-db
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: example
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mariadb/db:/var/lib/mysql

volumes:
  mongodb_data:
    driver: local
  mariadb_data:
    driver: local
